Document: cavif
Title: Debian cavif Manual
Author: <insert document author here>
Abstract: This manual describes what cavif is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cavif/cavif.sgml.gz

Format: postscript
Files: /usr/share/doc/cavif/cavif.ps.gz

Format: text
Files: /usr/share/doc/cavif/cavif.text.gz

Format: HTML
Index: /usr/share/doc/cavif/html/index.html
Files: /usr/share/doc/cavif/html/*.html
